from feature.ngram_features import NGramFeatures
from feature.extended_surface_features import ExtendedSurfaceFeatures
from feature.subjectivity_features import SubjectivityFeatures
from feature.word2vec import Word2Vec
from feature.word2vec_more import Word2VecMore
from feature.keywords_features import KeywordFeatures
from feature.doc2vec_features import Doc2VecFeatures
from feature.topic_features import TopicFeatures
from feature.meta_features import MetaFeatures
from feature.text_features import TextFeatures
from feature.semantic_features import SemanticFeatures
from feature.cnn_classification import CNN_Classification
from feature.ngram_headline_features import NGramHeadlineFeatures
from feature.ngram_first_page_features import NGramFirstPageFeatures
from feature.uids_first_page_features import UidsFirstPageFeatures
from feature.annotation_features import AnnotationFeatures
import feature.tsagkias
import feature.napoles
import feature.bandari
