from feature.ngram_features import NGramFeatures
from feature.extended_surface_features import ExtendedSurfaceFeatures
from feature.subjectivity_features import SubjectivityFeatures
from feature.word2vec import Word2Vec
from feature.doc2vec_features import Doc2VecFeatures
from feature.topic_features import TopicFeatures
from feature.meta_features import MetaFeatures
from feature.text_features import TextFeatures
from feature.semantic_features import SemanticFeatures
from feature.cnn_classification import CNN_Classification
import feature.tsagkias
import feature.napoles
import feature.bandari